EnrollmentListView UI 및 sorting 수정
Team-BUNT/ClassManager pull request #16
Opened 2022-10-24 08:34 UTC by namgeon1106

## 개요
* `EnrollmentListView`의 UI 및 sorting 방식 수정

## 작업 내용
* 홀 이름 뒤에 "홀" 붙이기
* 연락처 왼쪽 정렬
* 화면 좌우 패딩 20px
* 상단 배너 세 줄로 수정
* back button에서 "Back"를 삭제
* 신청내역 정렬 로직 변경

## 고민사항
* 없음

## 테스트 방법(optional)
* `EnrollmentListView`의 preview 확인

## 스크린샷
<img width="228" alt="스크린샷 2022-10-24 오후 5 32 58" src="https://user-images.githubusercontent.com/40821203/197483289-978d21bf-821e-4dce-8bde-45759bfc9614.png">

2022-10-24 11:48 UTC, jsh9611 requested changes
P1: EnrollmentListView에서 getFormattedPhoneNumberString라는 함수에 문제가 있는 것 같아.
파이어베이스 테스트하다가 발견했는데 휴대폰 번호가 이상하게 입력이 된 경우에는 에러가 발생하는듯.
정상적인 전화번호인지 체크하는 로직이 필요할 것 같고 확인이 된 전화번호에 대해서만 separatedBy를 하도록 수정이 필요해보여.

그리고 Assignees, Labels, Projects도 체크 부탁해😘

2022-10-24 11:48 UTC, jsh9611 commented on ClassManager/Model/Enrollment.swift
> +        self.enrolledDate = (documentSnapShot["enrolledDate"] as? Timestamp)?.dateValue() ?? Date()
P3: 이 부분 그때 급하게 수정했던걸로 기억하는데 너무 좋은듯

2022-10-24 11:48 UTC, jsh9611 commented on ClassManager/View/EnrollmentListView.swift
> +                Text((enrolledClass.hall?.name ?? "기본") + " 홀")
P3: 나중에 논의가 필요한 부분

2022-10-24 14:20 UTC, namgeon1106 commented on ClassManager/Model/Enrollment.swift
> +        self.enrolledDate = (documentSnapShot["enrolledDate"] as? Timestamp)?.dateValue() ?? Date()
이거 때문에 preview가 crash 되었어서 주의하자

2022-10-25 06:20 UTC, jsh9611 approved these changes

2022-10-25 06:21 UTC, merged